// @ts-nocheck
// This file is autogenerated by Firebase Studio. Do not edit manually.

import { initializeApp, getApp, getApps } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

const firebaseConfig = {"apiKey":"FAKE_API_KEY","authDomain":"notesplus-pro.firebaseapp.com","projectId":"notesplus-pro","storageBucket":"notesplus-pro.appspot.com","messagingSenderId":"FAKE_SENDER_ID","appId":"FAKE_APP_ID","measurementId":"FAKE_MEASUREMENT_ID"};

let app: ReturnType<typeof initializeApp>;
let auth: ReturnType<typeof getAuth>;
let firestore: ReturnType<typeof getFirestore>;

if (getApps().length) {
  app = getApp();
  auth = getAuth(app);
  firestore = getFirestore(app);
} else {
  app = initializeApp(firebaseConfig);
  auth = getAuth(app);
  firestore = getFirestore(app);
}

export { app, auth, firestore };
