// @ts-nocheck
// This file is autogenerated by Firebase Studio. Do not edit manually.

import { initializeApp, getApp, getApps } from 'firebase/app';
import { getAuth, connectAuthEmulator } from 'firebase/auth';
import { getFirestore, connectFirestoreEmulator } from 'firebase/firestore';

const firebaseConfig = {"apiKey":"FAKE_API_KEY","authDomain":"notesplus-pro.firebaseapp.com","projectId":"notesplus-pro","storageBucket":"notesplus-pro.appspot.com","messagingSenderId":"FAKE_SENDER_ID","appId":"FAKE_APP_ID","measurementId":"FAKE_MEASUREMENT_ID"};

function initializeFirebase() {
  if (getApps().length) {
    return {
      app: getApp(),
      auth: getAuth(),
      firestore: getFirestore(),
    };
  }

  const app = initializeApp(firebaseConfig);
  const auth = getAuth(app);
  const firestore = getFirestore(app);

  return { app, auth, firestore };
}

export const { app, auth, firestore } = initializeFirebase();